try {

    myFunction();

} catch(error) {
    console.log(error);
} finally {
    console.log('Finally runs regardless ')
}
console.log('WE ARE HERE THOUGH')


// array = [44, 88, 90, 1232, 23,9,4,1, 0]
// console.log(array.sort((a,b)=>a-b))